// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_fish_trap = "CgkIj4zC1e4JEAIQCA"; // <GPGSID>
        public const string achievement_survival_of_the_fittest = "CgkIj4zC1e4JEAIQEQ"; // <GPGSID>
        public const string achievement_where_no_man_has_gone_before = "CgkIj4zC1e4JEAIQFA"; // <GPGSID>
        public const string achievement_take_that_tuna = "CgkIj4zC1e4JEAIQDg"; // <GPGSID>
        public const string achievement_this_is_madness = "CgkIj4zC1e4JEAIQFQ"; // <GPGSID>
        public const string achievement_baby_fisher = "CgkIj4zC1e4JEAIQAQ"; // <GPGSID>
        public const string achievement_swift_learner = "CgkIj4zC1e4JEAIQCw"; // <GPGSID>
        public const string achievement_fisher = "CgkIj4zC1e4JEAIQBw"; // <GPGSID>
        public const string achievement_sunbath = "CgkIj4zC1e4JEAIQCQ"; // <GPGSID>
        public const string achievement_order_66 = "CgkIj4zC1e4JEAIQEw"; // <GPGSID>
        public const string achievement_professional_fisher = "CgkIj4zC1e4JEAIQAw"; // <GPGSID>
        public const string achievement_meaning_of_life = "CgkIj4zC1e4JEAIQEg"; // <GPGSID>
        public const string achievement_electoconvulsive_therapy = "CgkIj4zC1e4JEAIQCg"; // <GPGSID>
        public const string achievement_hero_of_the_colony = "CgkIj4zC1e4JEAIQDw"; // <GPGSID>
        public const string achievement_dinner_in_hell = "CgkIj4zC1e4JEAIQDQ"; // <GPGSID>
        public const string achievement_i_came_i_saw_i_conquered = "CgkIj4zC1e4JEAIQEA"; // <GPGSID>
        public const string achievement_extinction = "CgkIj4zC1e4JEAIQBg"; // <GPGSID>
        public const string achievement_defender_of_the_outpost = "CgkIj4zC1e4JEAIQDA"; // <GPGSID>
        public const string achievement_the_overfisher = "CgkIj4zC1e4JEAIQBQ"; // <GPGSID>
        public const string achievement_defishenator = "CgkIj4zC1e4JEAIQBA"; // <GPGSID>
        public const string achievement_fishermans_apprentice = "CgkIj4zC1e4JEAIQAg"; // <GPGSID>

}

